# Generated by Django 5.1.7 on 2025-04-19 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, help_text='Введите UID юзера', null=True, verbose_name='UID юзера')),
                ('name', models.CharField(blank=True, help_text='Введите логин', max_length=18, null=True, verbose_name='Логин юзера')),
                ('role', models.IntegerField(blank=True, help_text='Введите роль юзера (1-верифицирован, 2-админ)', null=True, verbose_name='Роль юзера')),
                ('mute', models.IntegerField(help_text='Введите статус блокировки голоса бзера (0-нет, 1-да)', verbose_name='Блокировка голоса юзера')),
                ('block', models.IntegerField(help_text='Введите статус блокировки юзера (0-нет, 1-да)', verbose_name='Статус блокировки юзера')),
                ('last_ip', models.GenericIPAddressField(blank=True, help_text='Введите последний айпи юзера', null=True, verbose_name='IP юзера')),
                ('date_of_create', models.DateField(blank=True, help_text='Введите дату создания юзера', null=True, verbose_name='Дата создания юзера')),
            ],
        ),
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, help_text='Дата окончания блокировки', null=True, verbose_name='Дата окончания блокировки юзера')),
                ('name', models.ForeignKey(blank=True, help_text='Имя нарушителя', null=True, on_delete=django.db.models.deletion.CASCADE, to='clydechat.user', verbose_name='Имя нарушителя')),
            ],
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, help_text='Дата окончания блокировки', null=True, verbose_name='Дата окончания блокировки юзера')),
                ('ip', models.ForeignKey(blank=True, help_text='IP нарушителя', null=True, on_delete=django.db.models.deletion.CASCADE, to='clydechat.user', verbose_name='IP нарушителя')),
            ],
        ),
    ]
