# Generated by Django 6.0.6 on 2026-06-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clydechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BannedIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NtIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.IntegerField(default=0, help_text='Введите статус блокировки юзера (0-нет, 1-да)', verbose_name='Статус блокировки юзера'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mute',
            field=models.IntegerField(default=0, help_text='Введите статус блокировки голоса бзера (0-нет, 1-да)', verbose_name='Блокировка голоса юзера'),
        ),
    ]
